# Generated by Django 4.0.3 on 2022-06-04 18:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('persons', '0003_alter_person_options_alter_person_created_at_and_more'),
        ('stands', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stand',
            options={'ordering': ['name'], 'verbose_name': 'Barraca', 'verbose_name_plural': 'Barracas'},
        ),
        migrations.AlterField(
            model_name='stand',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Ativa'),
        ),
        migrations.AlterField(
            model_name='stand',
            name='contact',
            field=models.CharField(help_text='Telefone ou celular do responsável pela barraca', max_length=100, null=True, verbose_name='Contato'),
        ),
        migrations.AlterField(
            model_name='stand',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação'),
        ),
        migrations.AlterField(
            model_name='stand',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_%(class)ss', to=settings.AUTH_USER_MODEL, verbose_name='Criado por'),
        ),
        migrations.AlterField(
            model_name='stand',
            name='manager',
            field=models.ForeignKey(help_text='Responsável pela barraca', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stand_manager', to='persons.person', verbose_name='Responsável'),
        ),
        migrations.AlterField(
            model_name='stand',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='stand',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Data de Atualização'),
        ),
        migrations.AlterField(
            model_name='stand',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='updated_%(class)ss', to=settings.AUTH_USER_MODEL, verbose_name='Atualizado por'),
        ),
    ]
