# Generated by Django 4.0.3 on 2022-09-08 02:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('persons', '0001_initial'),
        ('stands', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='stand',
            field=models.ForeignKey(blank=True, help_text='Selecione a barraca em que a pessoa trabalha.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='staff', to='stands.stand', verbose_name='Barraca'),
        ),
        migrations.AddField(
            model_name='person',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='updated_%(class)ss', to=settings.AUTH_USER_MODEL, verbose_name='Atualizado por'),
        ),
        migrations.AddField(
            model_name='person',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='person', to=settings.AUTH_USER_MODEL, verbose_name='Usuário'),
        ),
    ]
