# Generated by Django 4.1.1 on 2022-09-17 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("persons", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="person",
            name="active",
            field=models.BooleanField(default=True, verbose_name="Ativo"),
        ),
    ]
