# Generated by Django 4.0.1 on 2022-01-15 23:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stands', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stand',
            name='created_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
