# Generated by Django 4.0.1 on 2022-01-15 23:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stands', '0002_stand_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='stand',
            name='updated_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
