# Generated by Django 4.0.3 on 2022-06-04 18:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('measurement_units', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='measurementunit',
            options={'ordering': ['name'], 'verbose_name': 'Unidade de Medida', 'verbose_name_plural': 'Unidades de Medidas'},
        ),
        migrations.AlterField(
            model_name='measurementunit',
            name='abbreviation',
            field=models.CharField(help_text='Ex: kg, L, m, etc.', max_length=10, verbose_name='Abreviação'),
        ),
        migrations.AlterField(
            model_name='measurementunit',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação'),
        ),
        migrations.AlterField(
            model_name='measurementunit',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_%(class)ss', to=settings.AUTH_USER_MODEL, verbose_name='Criado por'),
        ),
        migrations.AlterField(
            model_name='measurementunit',
            name='name',
            field=models.CharField(help_text='Nome da unidade de medida', max_length=100, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='measurementunit',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Data de Atualização'),
        ),
        migrations.AlterField(
            model_name='measurementunit',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='updated_%(class)ss', to=settings.AUTH_USER_MODEL, verbose_name='Atualizado por'),
        ),
    ]
