# Generated by Django 4.0.3 on 2022-06-04 18:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0003_alter_person_options_alter_person_created_at_and_more'),
        ('stands', '0002_alter_stand_options_alter_stand_active_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0002_alter_product_options_alter_product_created_at_and_more'),
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transaction',
            options={'ordering': ['-created_at', '-updated_at'], 'verbose_name': 'Movimentação', 'verbose_name_plural': 'Movimentações'},
        ),
        migrations.AlterField(
            model_name='transaction',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_%(class)ss', to=settings.AUTH_USER_MODEL, verbose_name='Criado por'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='observation',
            field=models.TextField(blank=True, null=True, verbose_name='Observações'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='operation',
            field=models.CharField(choices=[('E', 'Entrada'), ('S', 'Saida')], default='S', help_text='Entrada: produtos entrando no almoxarifado<br>Saída: produtos saindo do almoxarifado', max_length=1, verbose_name='Operação'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='person',
            field=models.ForeignKey(help_text='Pessoa responsável pela movimentação', on_delete=django.db.models.deletion.CASCADE, to='persons.person', verbose_name='Pessoa'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='price',
            field=models.IntegerField(help_text='Valor global da movimentação em centavos; 0 (zero) para saídas internas e devoluções', verbose_name='Preço'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product', verbose_name='Produto'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='quantity',
            field=models.FloatField(verbose_name='Quantidade'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='stand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stands.stand', verbose_name='Barraca'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Data de Atualização'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='updated_%(class)ss', to=settings.AUTH_USER_MODEL, verbose_name='Atualizado por'),
        ),
        migrations.CreateModel(
            name='TransactionType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Data de Atualização')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nome')),
                ('description', models.TextField(blank=True, help_text='Descrição do tipo de movimentação', max_length=500, null=True, verbose_name='Descrição')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_%(class)ss', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='updated_%(class)ss', to=settings.AUTH_USER_MODEL, verbose_name='Atualizado por')),
            ],
            options={
                'verbose_name': 'Tipo de movimentação',
                'verbose_name_plural': 'Tipos de movimentação',
                'ordering': ['name'],
            },
        ),
        migrations.AlterField(
            model_name='transaction',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transactions.transactiontype', verbose_name='Tipo'),
        ),
    ]
