# Generated by Django 4.1.1 on 2022-09-14 01:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("transactions", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="transaction",
            options={
                "ordering": ["-datetime"],
                "verbose_name": "Movimentação",
                "verbose_name_plural": "Movimentações",
            },
        ),
    ]
