# Generated by Django 4.1.1 on 2022-09-24 02:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [
        ("transactions", "0002_transaction_from_stand_transaction_to_stand"),
        ("transactions", "0003_transactiontype_default_from_stand_and_more"),
        ("transactions", "0004_alter_transaction_stand"),
    ]

    dependencies = [
        ("transactions", "0001_initial"),
        ("stands", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="from_stand",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="from_stand",
                to="stands.stand",
                verbose_name="De",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="transaction",
            name="to_stand",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="to_stand",
                to="stands.stand",
                verbose_name="Para",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="transactiontype",
            name="default_from_stand",
            field=models.ForeignKey(
                blank=True,
                help_text="Barraca padrão para executar este tipo de movimentação",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="default_to_stand",
                to="stands.stand",
                verbose_name='Padrão para campo "De:"',
            ),
        ),
        migrations.AddField(
            model_name="transactiontype",
            name="default_to_stand",
            field=models.ForeignKey(
                blank=True,
                help_text="Barraca padrão para receber este tipo de movimentação",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="default_from_stand",
                to="stands.stand",
                verbose_name='Padrão para campo "Para:"',
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="stand",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="stands.stand",
                verbose_name="Barraca",
            ),
        ),
    ]
