# Generated by Django 4.0.3 on 2022-06-04 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_alter_transaction_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transactiontype',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='transactiontype',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='transactiontype',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='transactiontype',
            name='updated_by',
        ),
    ]
