# Generated by Django 4.0.3 on 2022-06-04 18:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0003_remove_transactiontype_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='date',
            field=models.DateField(auto_now_add=True, default=datetime.datetime(2022, 6, 4, 15, 49, 58, 827573), help_text='Data da movimentação', verbose_name='Data'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='transaction',
            name='price',
            field=models.IntegerField(help_text='Valor global da movimentação <b>em centavos</b>; 0 (zero) para saídas internas e devoluções', verbose_name='Preço'),
        ),
    ]
