# Generated by Django 4.0.3 on 2022-06-04 18:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0004_transaction_date_alter_transaction_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='date',
        ),
        migrations.AddField(
            model_name='transaction',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 4, 15, 55, 6, 779375), help_text='Data e hora da movimentação', verbose_name='Data e Hora'),
            preserve_default=False,
        ),
    ]
