name: Deploy Django App

on:
  push:
    branches: [main]

jobs:
  build:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Deploying Django App
        uses: easingthemes/ssh-deploy@main
        env:
          SOURCE: "./"
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          REMOTE_HOST: ${{ secrets.SSH_REMOTE_HOST }}
          REMOTE_USER: ${{ secrets.SSH_REMOTE_USER }}
          TARGET: ${{ secrets.SSH_REMOTE_TARGET }}
